### ISSUE TITLE
Change CharacterCreate to accept character data

### ISSUE THREAD

**Issue by aroman** [AEPi-AK/character-server#1]
Okay so it turns out that the current `CreateCharacter` endpoint is not very helpful.

The endpoint should actually accept a JSON payload like:

``` json
{
  "race": "human",
  "strength": 14,
  "dexterity": 14,
  "wisdom": 14,
  "data": "some string"
}
```

Where the `race` attribute can be one of `"human"`, `"elf"`, or `"dwarf"`, and the stat attributes will be integers in the range [1,20].

It should return the equivalent of a `GetCharacter` request, that is, return the current character data, including the new data form the request. So, for example:

``` json
{
  "id": "e855b64ddf933e053f57202c51ce2c9ccc7291c902dddfd55870789609e10d6d",
  "num": 453,
  "race": "human",
  "strength": 14,
  "dexterity": 14,
  "wisdom": 14
}
```

**Comment by jbrown215** [comment]
This is done, updating docs
