### ISSUE TITLE
2016/04/13 01:47:34 http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by aroman** [AEPi-AK/character-server#15]
not sure what this error is about exactly, but it probably should be fixed, even if it is harmless

**Comment by jbrown215** [comment]
figured it out-- you can't Write before your WriteHeader, otherwise it defaults to status 200

**Comment by aroman** [comment]
still getting this issue, can you investigate? here's a log:

~/D/g/s/g/A/character-server ❯❯❯ ./character-server                                                 ⏎ master ✭
INFO[0000] Listening on port 8000
INFO[0037] Received character display request            id=382cab52583acd9f1c96ae365de1512e30908337b6f1792191fcab18091dad7f time=2016-04-13 18:53:45.071369449 -0400 EDT
INFO[0044] Received character display request            id=f0f84e4f236af7064df75ee4f360fe779aee09009ce88d5b79d43995ee555db5 time=2016-04-13 18:53:52.093614918 -0400 EDT
WARN[0044] Character not found                           id=f0f84e4f236af7064df75ee4f360fe779aee09009ce88d5b79d43995ee555db5 time=2016-04-13 18:53:52.117248163 -0400 EDT
INFO[0045] Received character create request             time=2016-04-13 18:53:53.928757144 -0400 EDT
f0f84e4f236af7064df75ee4f360fe779aee09009ce88d5b79d43995ee555db5
INFO[0060] Received character display request            id=382cab52583acd9f1c96ae365de1512e30908337b6f1792191fcab18091dad7f time=2016-04-13 18:54:08.467869712 -0400 EDT
INFO[0076] Received character display request            id=382cab52583acd9f1c96ae365de1512e30908337b6f1792191fcab18091dad7f time=2016-04-13 18:54:24.669671924 -0400 EDT
INFO[0081] Received character display request            id=382cab52583acd9f1c96ae365de1512e30908337b6f1792191fcab18091dad7f time=2016-04-13 18:54:29.270766398 -0400 EDT
INFO[0086] Received character update request             id=382cab52583acd9f1c96ae365de1512e30908337b6f1792191fcab18091dad7f time=2016-04-13 18:54:34.566000725 -0400 EDT
2016/04/13 18:54:34 http: multiple response.WriteHeader calls
^C
~/D/g/s/g/A/character-server ❯❯❯ gs

**Comment by jbrown215** [comment]
same issue was in the update code. this is done
