### ISSUE TITLE
panic should not send empty response

### ISSUE THREAD

**Issue by aroman** [AEPi-AK/character-server#4]
currently if, something goes wrong (e.g. the client sends JSON that isn't what the server expects), the server will panic resulting in HTTP 204 No Content. This isn't what we want. We probably want an appropriate [4xx error](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error).

**Comment by jbrown215** [comment]
do you want me to do this directly in the server or are you still planning on writing middleware for this

**Comment by aroman** [comment]
i'm not planning on writing anything :^) 

I think middleware is the way to do it, so you don't have to copypasta in every endpoint, but maybe I'm wrong. Do it however you'd prefer and if we really want we can refactor later.

**Comment by jbrown215** [comment]
nice jew nose :^)

**Comment by jbrown215** [comment]
close and comment looks way too similar to cancel

**Comment by jbrown215** [comment]
I've updated the code to fix this. Take a look when you get a chance pls bb girl

**Comment by jbrown215** [comment]
i've convinced myself that i have fixed this at this point
