### ISSUE TITLE
change CharacterShow functionality

### ISSUE THREAD

**Issue by aroman** [AEPi-AK/character-server#7]
currently, CharacterShow accepts a single "identifier" parameter, and then uses FindCharacter to look up the character.

This is fine for looking up a character by ID, but I need to be able to look up a character by the raw card data. Use case: at character creation kiosk, you swipe card. I need to ask the server if there's a character with that ID before. This can't be done right now, since I'd need the hashed value or the character #, but I don't have either at the just-swiped-card phase.

So, I propose that CharacterShow accepts multiple query parameters: `data` and `num`. I don't think there's a reason I'd need to look up by ID directly yet, so forget that. So basically:

`/character?data=abc123` => hash(data) => look up character by ID/pro_ID and return it if it exists, else 404
`/character?num=abc` => => look up character by `num` and return it if it exists, else 404

Also, note that you will NOT be able to use `Atoi` for this because `data` will often look like a number (actually, almost always). Hence why you need two parameters, not just 1 with try/fail logic.

**Comment by jbrown215** [comment]
seriously though? like come on. make it hard. i dare you to make it hard, avi. you couldnt make it too hard for me if you tried.

EDIT: i forgot the comma before avi so i added it in. GOOD GRAMMAR
